version: '2.4'
services:
  nginx:
    image: nginx:alpine
    restart: always
    network_mode: host
    depends_on:
      - "slurm-0"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/certs/slurmrest.csquare.gcloud.crt:/etc/ssl/certs/slurmrest.csquare.gcloud.crt
      - ./conf/nginx/certs/slurmrest.csquare.gcloud.key:/etc/ssl/certs/slurmrest.csquare.gcloud.key
    # ports:
    #   - 443:443
    # networks:
    #   - slurmctl-net

  slurmdb:
    image: ghcr.io/squarefactory/slurm:latest-db
    restart: always
    network_mode: host
    hostname: slurmdb
    container_name: slurmdb
    entrypoint: ['sh', '-c', 'update-ca-trust && /init']
    # ports:
    #   - 6819:6819
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem:ro
      - ./secrets/sssd/:/secrets/sssd/:ro
      - ./secrets/munge/:/secrets/munge/:ro
      - ./secrets/slurm/:/secrets/slurm/:ro
      - ./conf/slurm:/etc/slurm:ro
      - /mnt/nfs/archive:/archive

  slurmctl:
    image: ghcr.io/squarefactory/slurm:latest-controller
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - "slurmdb"
    hostname: slurmctl
    container_name: slurm-controller
    entrypoint: ['sh', '-c', 'update-ca-trust && /init']
    # ports:
    #   - 6817:6817
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem:ro
      - ./secrets/sssd/:/secrets/sssd/:ro
      - ./secrets/munge/:/secrets/munge/:ro
      - ./secrets/slurm/:/secrets/slurm/:ro
      - ./conf/slurm:/etc/slurm:ro
      - ./state/slurmctl:/var/spool/slurmctl
    # networks:
    #   - slurmctl-net

  slurm-0:
    image: ghcr.io/squarefactory/slurm:latest-compute
    restart: always
    network_mode: host
    depends_on:
      - "slurmctl"
    hostname: slurm-0
    container_name: slurm-0
    entrypoint: ['sh', '-c', 'update-ca-trust && /init']
    # expose:
    #   - "6820"
    #   - "6818"
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem:ro
      - ./secrets/sssd/:/secrets/sssd/:ro
      - ./secrets/munge/:/secrets/munge/:ro
      - ./secrets/slurm/:/secrets/slurm/:ro
      - ./conf/slurm:/etc/slurm:ro
      - ./state/slurmd:/var/spool/slurmd


  slurmrest:
    image: ghcr.io/squarefactory/slurm:latest-rest
    restart: always
    depends_on:
      - "slurmctl"
    entrypoint: ['sh', '-c', 'update-ca-trust && /init']
    expose:
      - "6820"
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/pki/ca-trust/source/anchors/csquare.gcloud.ca.pem:ro
      - ./secrets/sssd/:/secrets/sssd/:ro
      - ./secrets/munge/:/secrets/munge/:ro
      - ./secrets/slurm/:/secrets/slurm/:ro
      - ./conf/slurm:/etc/slurm:ro
    cpus: 0.50
    mem_reservation: 512M
    mem_limit: 512M
    memswap_limit: 512M
    # networks:
    #   - slurmctl-net
