version: '3.9'

services:
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   network_mode: host
  #   depends_on:
  #     - "slurm-0"
  #   volumes:
  #     - ./logs/nginx:/var/log/nginx
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs/slurmrest.csquare.gcloud.crt:/etc/ssl/certs/slurmrest.csquare.gcloud.crt
  #     - ./nginx/certs/slurmrest.csquare.gcloud.key:/etc/ssl/certs/slurmrest.csquare.gcloud.key

  hn0:
    image: slurm
    pull_policy: never
    build:
      context: ./slurm
      dockerfile: Dockerfile
      target: slurm-head
    hostname: hn0
    container_name: hn0
    ports:
      - 10.5.0.5:22:22
    networks:
      vpc:
        ipv4_address: 10.5.0.5
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./secrets/sssd:/secrets/sssd:ro
      - ./secrets/munge:/secrets/munge:ro
      - ./secrets/slurm:/secrets/slurm:ro
      - ./conf/slurm:/etc/slurm:ro
      - ./conf/sshd_config:/etc/ssh/sshd_config:ro
      - ./secrets/ssh:/secrets/ssh:ro
      - ./logs/slurm:/var/log/slurm
      - /opt/cvmfs:/opt/cvmfs
      - /opt/gentoo:/opt/gentoo
      - ldap-users:/home/ldap-users
      - jobs-logs:/opt/jobs-logs
      - images:/opt/images
      - experiments:/opt/experiments

networks:
  vpc:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
          gateway: 10.10.2.1

volumes:
  ldap-users:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/ldap-users"
  jobs-logs:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/jobs-logs"
  images:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/images"
  experiments:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/experiments"
