version: '3.9'
services:
  slurmctl:
    image: slurm-base
    restart: always
    pull_policy: never
    privileged: true
    network_mode: host
    command: ['slurmctld']
    build:
      context: ./slurm
      dockerfile: Dockerfile
    hostname: slurmctl
    container_name: slurmctl
    dns:
      - 10.10.2.10
    # ports:
    #   - 6817:6817
    volumes:
      - /home/user/nfs-mount/ldap-certificate.pem:/etc/ssl/certs/ldap-certificate.pem:ro
      - /home/user/nfs-mount/sssd.conf:/etc/sssd/sssd.conf:ro
      - /home/user/nfs-mount/munge.key:/secrets/munge.key:ro
      - /home/user/nfs-mount/slurmctl/jwt_hs256.key:/secrets/jwt_hs256.key:ro
      - /home/user/nfs-mount/site-specific/sweden/slurmctl:/etc/slurm:ro
      - ./logs:/var/log/slurm
      - ./state:/var/spool/slurmctl
      - ./bin/fakemail:/usr/bin/fakemail:ro
