version: '3.9'
services:
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - "slurmd-0"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/slurmrest.csquare.gcloud.chained.crt:/etc/ssl/certs/slurmrest.csquare.gcloud.chained.crt
      - ./nginx/certs/slurmrest.csquare.gcloud.key:/etc/ssl/certs/slurmrest.csquare.gcloud.key
    ports:
      - 80:80
      - 443:443
    networks:
      - slurmctl-net

  slurmctl:
    image: slurmctl
    restart: always
    pull_policy: never
    build:
      context: ./slurmctl
      dockerfile: Dockerfile
    hostname: slurmctl
    container_name: slurmctl
    ports:
      - 6817:6817
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/ssl/certs/ldap-certificate.pem:ro
      - /etc/sssd/sssd.conf:/etc/sssd/sssd.conf:ro
      - ./secrets/munge.key:/secrets/munge.key:ro
      - ./secrets/jwt_hs256.key:/secrets/jwt_hs256.key:ro
      - ./conf:/etc/slurm:ro
    networks:
      - slurmctl-net

  slurmd-0:
    image: slurmd
    restart: always
    pull_policy: never
    build:
      context: ./slurmd
      dockerfile: Dockerfile
    depends_on:
      - "slurmctl"
    hostname: slurmd-0
    container_name: slurmd-0
    privileged: true  # Only used for REST Api
    expose:
      - "6820"
      - "6818"
    volumes:
      - /etc/ssl/certs/ldap-certificate.pem:/etc/ssl/certs/ldap-certificate.pem:ro
      - /etc/sssd/sssd.conf:/etc/sssd/sssd.conf:ro
      - ./secrets/munge.key:/secrets/munge.key:ro
      - ./secrets/jwt_hs256.key:/secrets/jwt_hs256.key:ro
      - ./conf:/etc/slurm:ro
    networks:
      - slurmctl-net
    cap_add:
      - IPC_OWNER  # Only used for REST Api

networks:
  slurmctl-net:
