version: '3.9'

services:
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   network_mode: host
  #   depends_on:
  #     - "slurm-0"
  #   volumes:
  #     - ./logs/nginx:/var/log/nginx
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs/slurmrest.csquare.gcloud.crt:/etc/ssl/certs/slurmrest.csquare.gcloud.crt
  #     - ./nginx/certs/slurmrest.csquare.gcloud.key:/etc/ssl/certs/slurmrest.csquare.gcloud.key

  slurm-0:
    image: slurm
    restart: always
    pull_policy: never
    network_mode: host
    build:
      context: ./slurm
      dockerfile: Dockerfile
      target: slurm-slurmd
    hostname: slurm-0
    container_name: slurm-0
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./secrets/sssd:/secrets/sssd:ro
      - ./secrets/munge:/secrets/munge:ro
      - ./secrets/slurm:/secrets/slurm:ro
      - ./conf/slurm.conf:/etc/slurm/slurm.conf:ro
      - ./conf/sshd_config:/etc/ssh/sshd_config:ro
      - ./secrets/ssh:/secrets/ssh:ro
      - ./logs/slurm:/var/log/slurm
      - /opt/cvmfs:/opt/cvmfs
      - /opt/gentoo:/opt/gentoo

volumes:
  ldap-users:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/ldap-users"
  jobs-logs:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/jobs-logs"
  images:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/images"
  experiments:
    driver_opts:
      type: "nfs"
      o: "nfsvers=3,addr=10.10.2.11,nolock,soft,rw"
      device: ":/mnt/pool1/compute-nodes/experiments"
