version: '3.9'
services:
  slurmctl:
    image: slurm-slurmctl
    restart: always
    pull_policy: never
    privileged: true
    network_mode: host
    build:
      context: ./slurm
      dockerfile: Dockerfile
    hostname: slurmctl
    container_name: slurmctl
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./conf/slurm:/etc/slurm:ro
      - ./secrets/sssd:/secrets/sssd:ro
      - ./secrets/munge:/secrets/munge:ro
      - ./secrets/slurm:/secrets/slurm:ro
      - ./secrets/ssh:/root/.ssh:ro
      #- /home/user/nfs-mount/site-specific/sion/slurmctl-keys/id_rsa:/root/.ssh/id_rsa:ro
      #- /home/user/nfs-mount/site-specific/sion/slurmctl-keys/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ./tmp:/tmp
      - ./beeond-status:/var/log/beeond
      - ./state:/var/spool/slurmctl
      - ./bin/fakemail:/usr/bin/fakemail:ro
