name: SLURM CI Without Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocky_version: ['8.5', '9.0']
        component: ['compute', 'controller', 'db', 'login', 'rest', 'prometheus-exporter']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./slurm/Dockerfile.rocky${{ matrix.rocky_version }}
          context: ./slurm
          platforms: linux/amd64
          push: false
          tags: squarefactory/slurm:latest-${{ matrix.component }}-rocky${{ matrix.rocky_version }}
          cache-to: type=gha,mode=max
          target: slurm-${{ matrix.component }}
