name: SLURM CI

on:
  push:

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocky_version: ['8.6', '9.2']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./slurm/Dockerfile.rocky${{ matrix.rocky_version }}
          context: ./slurm
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: slurm-base

  build-export:
    needs: [build-base]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocky_version: ['8.6', '9.2']
        component:
          - 'compute'
          - 'controller'
          - 'db'
          - 'login'
          - 'rest'
          - 'prometheus-exporter'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: docker/build-push-action@v5
        with:
          file: ./slurm/Dockerfile.rocky${{ matrix.rocky_version }}
          context: ./slurm
          platforms: linux/amd64
          push: false
          tags: deepsquare-io/slurm:latest-${{ matrix.component }}-rocky${{ matrix.rocky_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: slurm-${{ matrix.component }}

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the oci compatible version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          OCI_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/+/-/g')
          echo "VERSION=${OCI_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and export
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          file: ./slurm/Dockerfile.rocky${{ matrix.rocky_version }}
          context: ./slurm
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/deepsquare-io/slurm:latest-${{ matrix.component }}-rocky${{ matrix.rocky_version }}
            ghcr.io/deepsquare-io/slurm:${{ steps.get_version.outputs.VERSION }}-${{ matrix.component }}-rocky${{ matrix.rocky_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: slurm-${{ matrix.component }}
