name: SLURM CI Without Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rocky_version: ['8.6', '9.0']
        component:
          [
            'compute',
            'controller',
            'db',
            'login',
            'rest',
            'prometheus-exporter',
          ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./slurm/Dockerfile.rocky${{ matrix.rocky_version }}
          context: ./slurm
          platforms: linux/amd64
          push: false
          tags: squarefactory/slurm:latest-${{ matrix.component }}-rocky${{ matrix.rocky_version }}
          cache-to: type=gha,mode=max
          target: slurm-${{ matrix.component }}
