name: Check versions
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-updates:
    name: Check for updates
    runs-on: ubuntu-20.04
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update && sudo apt install -y python3 curl jq sed gawk
      - name: Update Dockerfile
        run: sh ./ci/version-checker.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update dependencies'
          delete-branch: true
          title: 'chore: update dependencies'
          branch: chore/update-dependencies
          token: ${{ steps.generate_token.outputs.token }}
          reviewers: |
            Darkness4
